### ISSUE TITLE
If jmh test will be just in root then NPE when jmh:run 

### ISSUE THREAD

**Issue by ghost** [ktoso/sbt-jmh#145]
Hi, folks

If I will create a benchmark directly in `src/main/scala` I receive NPE

```
java.lang.NullPointerException
        at org.openjdk.jmh.generators.reflection.RFClassInfo.getPackageName(RFClassInfo.java:51)
        at org.openjdk.jmh.generators.core.BenchmarkGenerator.validateBenchmark(BenchmarkGenerator.java:227)
        at org.openjdk.jmh.generators.core.BenchmarkGenerator.generate(BenchmarkGenerator.java:81)
        at org.openjdk.jmh.generators.bytecode.JmhBytecodeGenerator.main(JmhBytecodeGenerator.java:100)
        at pl.project13.scala.sbt.JmhPlugin$.internalGenerateBenchmarkSourcesAndResources(JmhPlugin.scala:125)
        at pl.project13.scala.sbt.JmhPlugin$.$anonfun$generateBenchmarkSourcesAndResources$2(JmhPlugin.scala:108)
        at sbt.util.FileFunction$.$anonfun$cached$1(FileFunction.scala:73)
        at sbt.util.FileFunction$.$anonfun$cached$4(FileFunction.scala:147)
        at sbt.util.Difference.apply(Tracked.scala:313)
        at sbt.util.Difference.apply(Tracked.scala:293)
        at sbt.util.FileFunction$.$anonfun$cached$3(FileFunction.scala:143)
        at sbt.util.Difference.apply(Tracked.scala:313)
        at sbt.util.Difference.apply(Tracked.scala:288)
        at sbt.util.FileFunction$.$anonfun$cached$2(FileFunction.scala:142)
        at pl.project13.scala.sbt.JmhPlugin$.generateBenchmarkSourcesAndResources(JmhPlugin.scala:110)
        at pl.project13.scala.sbt.JmhPlugin$.$anonfun$projectSettings$13(JmhPlugin.scala:66)
        at scala.Function1.$anonfun$compose$1(Function1.scala:44)
        at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
        at sbt.std.Transform$$anon$4.work(System.scala:64)
        at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
        at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
        at sbt.Execute.work(Execute.scala:266)
        at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
        at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

I'm not sure if that is made by design, but when you move benchmark class into any package inside `src/main/scala` it works.

**Comment by jiminhsieh** [comment]
@lozenko It seemed you met the same situation as #134. You can take a look at that issue.

**Comment by retronym** [comment]
I've submitted a fix to JMH for this to give a better error message: https://github.com/openjdk/jmh/pull/38/files
