### ISSUE TITLE
Cannot run JMH benchmarks with async-profiler for versions 0.3.5 and 0.3.6

### ISSUE THREAD

**Issue by plokhotnyuk** [ktoso/sbt-jmh#164]
Output with 0.3.5:
```
[info] Running (fork) org.openjdk.jmh.Main -jvmArgsAppend -XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints -prof jmh.extras.Async:event=cpu;dir=/tmp/profile-async;asyncProfilerDir=/home/andriy/Projects/com/github/jvm-profiling-tools/async-profiler;flameGraphDir=/home/andriy/Projects/com/github/brendangregg/FlameGraph;flameGraphOpts=--color,java;verbose=true -wi 5 -i 30 -p size=128 ArrayOfBooleansBenchmark.writeSprayJson
[info] java.lang.ClassNotFoundException: jmh.extras.Async
[error] Profilers failed to initialize, exiting.
[error] Nonzero exit code returned from runner: 1
[error] (jsoniter-scala-benchmark / Jmh / run) Nonzero exit code returned from runner: 1
```
Output with 0.3.6:
```
[error] Exception in thread "main" java.lang.UnsupportedClassVersionError: jmh/extras/Async has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
[error] 	at java.lang.ClassLoader.defineClass1(Native Method)
[error] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
[error] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[error] 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
[error] 	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
[error] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
[error] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
[error] 	at java.security.AccessController.doPrivileged(Native Method)
[error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error] 	at java.lang.Class.forName0(Native Method)
[error] 	at java.lang.Class.forName(Class.java:264)
[error] 	at org.openjdk.jmh.profile.ProfilerFactory.getProfiler(ProfilerFactory.java:76)
[error] 	at org.openjdk.jmh.profile.ProfilerFactory.getProfilerOrException(ProfilerFactory.java:37)
[error] 	at org.openjdk.jmh.runner.Runner.internalRun(Runner.java:238)
[error] 	at org.openjdk.jmh.runner.Runner.run(Runner.java:209)
[error] 	at org.openjdk.jmh.Main.main(Main.java:71)
[error] Nonzero exit code returned from runner: 1
[error] (jsoniter-scala-benchmark / Jmh / run) Nonzero exit code returned from runner: 1
[error] Total time: 4 s, completed Apr 15, 2019 8:50:45 PM
```

W/A is rolling back to 0.3.4 version

**Comment by retronym** [comment]
Merging with #165
