### ISSUE TITLE
IncompatibleClassChangeError with custom runner

### ISSUE THREAD

**Issue by yanns** [ktoso/sbt-jmh#66]
I just added `object CustomRunnerApp extends App`.
I do not use it.

By running:

```
jmh:run -i 1 -wi 1 -f1 -t1
```

I have the following exception:

```
Annotation generator had thrown the exception.
java.lang.IncompatibleClassChangeError: sphere.CustomRunnerApp and sphere.CustomRunnerApp$delayedInit$body disagree on InnerClasses attribute
    at java.lang.Class.getDeclaringClass0(Native Method)
    at java.lang.Class.getDeclaringClass(Class.java:1235)
    at java.lang.Class.getEnclosingClass(Class.java:1277)
    at java.lang.Class.getCanonicalName(Class.java:1392)
    at org.openjdk.jmh.generators.reflection.RFClassInfo.getQualifiedName(RFClassInfo.java:67)
    at org.openjdk.jmh.generators.core.BenchmarkGenerator.buildAnnotatedSet(BenchmarkGenerator.java:219)
    at org.openjdk.jmh.generators.core.BenchmarkGenerator.generate(BenchmarkGenerator.java:85)
    at org.openjdk.jmh.generators.bytecode.JmhBytecodeGenerator.main(JmhBytecodeGenerator.java:100)
    at pl.project13.scala.sbt.JmhPlugin$.pl$project13$scala$sbt$JmhPlugin$$internalGenerateBenchmarkSourcesAndResources(JmhPlugin.scala:81)
    at pl.project13.scala.sbt.JmhPlugin$$anonfun$2.apply(JmhPlugin.scala:64)
    at pl.project13.scala.sbt.JmhPlugin$$anonfun$2.apply(JmhPlugin.scala:62)
```

Should I remove this class from the jmh "transformations"?

**Comment by TimSoethout** [comment]
Any solution on this?
I have the same problem with a custom runner in the same module.

**Comment by Mefu** [comment]
I think I found a workaround it for now. Use a normal main function instead of extending App. Like do following instead of [example in readme](https://github.com/ktoso/sbt-jmh/blob/master/plugin/src/sbt-test/sbt-jmh/runMain/src/main/scala/com/example/CustomRunnerApp.scala)

```
package com.example

import java.io.{File, FileOutputStream}

import org.openjdk.jmh.results.RunResult
import org.openjdk.jmh.runner.Runner
import org.openjdk.jmh.runner.options.CommandLineOptions

object CustomRunnerApp {
  import scala.collection.JavaConversions._
  def main(args: Array[String]): Unit = {
    val opts = new CommandLineOptions(args: _*) // parse command line arguments, and then bend them to your will! ;-)

    val runner = new Runner(opts) // full access to all JMH features, you can also provide a custom output Format here

    val results = runner.run() // actually run the benchmarks

    val f = new FileOutputStream(new File("custom.out"))
    results.foreach { result: RunResult ⇒
      // usually you'd use these results to report into some external aggregation tool for example
      f.write(s"custom reporting result: ${result.getAggregatedResult.getPrimaryResult}".getBytes("UTF-8"))
    }
    f.close()
  }

}
```

I do not know if this would cause any other problems but it looks like working properly for me.

**Comment by TimSoethout** [comment]
Thanks @Mefu, this seems to work for me as well.

**Comment by sfosdal** [comment]
This worked for me as well.
