### ISSUE TITLE
java.lang.InternalError: Malformed class name on jmh:run

### ISSUE THREAD

**Issue by jrudnick** [ktoso/sbt-jmh#69]
Currently trying to run previously built/running benchmarks with `sbt-jmh` and appears to fail with a runtime error.  I have tried turning the example into something simple, which may help in reproducing.

scala version: 2.11.4
sbt version: 0.13.7
sbt-jmh version: 0.2.6 (also tried with 0.2.4, and it fails there now also)

The project is a multi-module project, where there is a `benchmarks` module containing the jmh benchmarks and has the JmhPlugin enabled.

Below, is a simple benchmark that can be run, in isolation:
```scala
package foo.bar

import org.openjdk.jmh.annotations.Benchmark

class Benchmarks {
  @Benchmark
  def helloWorldBench(): Unit = {
  }
}
```
If we put this file in the same directory, then we get the error seen below:
```scala
package foo.bar
object Bar {
  object Hello {
    //Note: if we move the trait below out of Hello, but within Bar it "fixes"
    trait Something
  }
}
```

Here is the general error observed: 
```
[info] Compiling 1 Scala source to ...
Processing 140 classes from /.../target/scala-2.11/classes with "reflection" generator
Writing out Java source to /.../target/scala-2.11/src_managed/jmh and resources to /.../target/scala-2.11/resource_managed/jmh
Annotation generator had thrown the exception.
java.lang.InternalError: Malformed class name
	at java.lang.Class.getSimpleName(Class.java:1330)
	at java.lang.Class.getCanonicalName(Class.java:1399)
	at org.openjdk.jmh.generators.reflection.RFClassInfo.getQualifiedName(RFClassInfo.java:67)
	at org.openjdk.jmh.generators.core.BenchmarkGenerator.buildAnnotatedSet(BenchmarkGenerator.java:226)
	at org.openjdk.jmh.generators.core.BenchmarkGenerator.generate(BenchmarkGenerator.java:85)
	at org.openjdk.jmh.generators.bytecode.JmhBytecodeGenerator.main(JmhBytecodeGenerator.java:100)
	at pl.project13.scala.sbt.JmhPlugin$.pl$project13$scala$sbt$JmhPlugin$$internalGenerateBenchmarkSourcesAndResources(JmhPlugin.scala:91)
	at pl.project13.scala.sbt.JmhPlugin$$anonfun$2.apply(JmhPlugin.scala:74)
	at pl.project13.scala.sbt.JmhPlugin$$anonfun$2.apply(JmhPlugin.scala:72)
	at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:186)
	at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:186)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:200)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:196)
	at sbt.Difference.apply(Tracked.scala:175)
	at sbt.Difference.apply(Tracked.scala:157)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:196)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:195)
	at sbt.Difference.apply(Tracked.scala:175)
	at sbt.Difference.apply(Tracked.scala:151)
	at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:195)
	at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:193)
	at pl.project13.scala.sbt.JmhPlugin$.pl$project13$scala$sbt$JmhPlugin$$generateBenchmarkSourcesAndResources(JmhPlugin.scala:76)
	at pl.project13.scala.sbt.JmhPlugin$$anonfun$projectSettings$9.apply(JmhPlugin.scala:42)
	at pl.project13.scala.sbt.JmhPlugin$$anonfun$projectSettings$9.apply(JmhPlugin.scala:42)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jrudnick** [comment]
After trying to reproduce with similar code above, in an isolated environment was not able to reproduce.  I will try to get a small, accurate reproducer and attach it to this issue or I will close the issue.

**Comment by jrudnick** [comment]
Updated the description with more specific steps towards basic reproduction.  This may be a known issue, but as it stands now is highly cryptic.  Maybe there is something that `sbt-jmh` can provide to make it less so.

**Comment by jrudnick** [comment]
Perhaps this is the root cause? https://issues.scala-lang.org/browse/SI-2034

**Comment by ktoso** [comment]
> It appears, that calling getCanonicalName on doubly nested (in objects) traits isn't something that Scala likes.

Yeah that's exactly the thing I was thinking about.
I think the fact of nesting inside classes already causes tricky name problems.
I'm not sure sbt-jmh is able to do anything about it, since it does not even own the thread (nor even jvm!) that this error will come up on...

I can't come up with a way to help out from my end on this one... would you mind if we close as scala issue?

**Comment by jrudnick** [comment]
I guess there is no way in `JmhPlugin.scala` to at least report the file that is providing the issue?

**Comment by ktoso** [comment]
I don't really see how we could, if people google for it they'll find this issue. 
I'll close for now. Thanks for the research though!

**Comment by jvican** [comment]
Also having the same problem. Unfortunately, the codebase I tried this on is huge and I cannot spend too much time on this. Sad to see that SI-2034 is still not solved.

**Comment by joshlemer** [comment]
@jrudnick while the exception does not inform you which class throws the exception, you can attach a debugger to an SBT task (for example in IntelliJ) and set a breakpoint at `java/lang/Class.java` line 1330 to inspect the name of the class that is allegedly malformed.

**Comment by Reeebuuk** [comment]
In my case it was an enumeratum object.

``` import enumeratum.{ Enum, EnumEntry }

  sealed trait Status extends EnumEntry

  object Status extends Enum[Status] {

    val values: scala.collection.immutable.IndexedSeq[Status] = findValues

    case object Draft extends Status
    ...
  }
```
java.lang.Class:1330

simpleName had value `Draft$` which breaks the `simpleName.charAt(0) != '$'` condition.

**Comment by atk91** [comment]
Is this ever going to be fixed?
